//ACTION TYPES FOR PRODUCT
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const UPDATE_HAS_NEXT_PAGE = 'UPDATE_HAS_NEXT_PAGE';
export const SET_PAGE = 'SET_PAGE';
export const SET_DISPLAY_ITEMS = 'SET_DISPLAY_ITEMS';
export const SET_SORT_OPTION = 'SET_SORT_OPTION';
export const SET_FILTER_OPTION = 'SET_FILTER_OPTION';
export const SET_QUERY = 'SET_QUERY';

//ACTION TYPES FOR CART
export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const GET_CART_TOTAL = 'GET_CART_TOTAL';
export const TOGGLE_CART_AMOUNT = 'TOGGLE_CART_AMOUNT';

//ACTION TYPES FOR COMPARE
export const CLEAR_COMPARE = 'CLEAR_COMPARE';
export const REMOVE_COMPARE_ITEM = 'REMOVE_COMPARE_ITEM';
export const ADD_COMPARE_ITEM = 'ADD_COMPARE_ITEM';

//ACTION TYPES FOR MODAL
export const OPEN_MESSAGE = 'OPEN_MESSAGE';
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';
